# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_PG_pw24/dds_PG_pw24.xci
# IP: The module: 'dds_PG_pw24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_PG_pw24/dds_PG_pw24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_PG_pw24'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_PG_pw24/dds_PG_pw24.xci
# IP: The module: 'dds_PG_pw24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_PG_pw24/dds_PG_pw24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_PG_pw24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
