# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_LUT_pw24_ow16/dds_LUT_pw24_ow16.xci
# IP: The module: 'dds_LUT_pw24_ow16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_LUT_pw24_ow16/dds_LUT_pw24_ow16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_LUT_pw24_ow16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_LUT_pw24_ow16/dds_LUT_pw24_ow16.xci
# IP: The module: 'dds_LUT_pw24_ow16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Documents/GitHub/RedPitayaMaster/fpga/project/redpitaya.srcs/sources_1/ip/dds_LUT_pw24_ow16/dds_LUT_pw24_ow16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_LUT_pw24_ow16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
